name: 'Poetry Install'
description: 'Install Poetry and have it then install package dependencies.'
inputs:
  create-virtualenv:
    description: 'Have poetry create a virtualenv for the project on installation.'
    required: false
    default: 'false'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
